# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Schedule001' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Eureka'
  pod 'Realm'
  pod 'RealmSwift'
  pod 'CSV.swift'
  pod 'R.swift'
  pod 'BTNavigationDropdownMenu'
  # Pods for Schedule001

end
